from pathlib import Path

from crya import App, ViteConfig

app = App(
    root_directory=Path(__file__).parent,
    vite=ViteConfig(
        hot_file="public/hot",  # written by dev server
        manifest="public/build/.vite/manifest.json",  # generated by vite build
        build_url="/build",  # URL prefix for built assets
        build_dir="public/build",  # directory to serve from
    ),
    routes=["routes.web"],
)
